spring:
  application:
    name: order
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: scott
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:orcl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
    bus:
      enabled: true
  rabbitmq:
      host: 104.224.142.248
     #port: 5672
      port: 5672
      username: guest
      password: guest
env:
  dev
management:
  endpoints:
    web:
      expose: "*"
